// Test bench generated by generator_verilog.py

`timescale 1ns / 1ps

module SectorProcessor_test();

reg clk;
reg reset;

initial begin
  reset = 1'b1;
  clk   = 1'b1;
end

initial begin
//  #540
  #1080
  reset = 1'b0;
end

reg en_proc = 1'b0;
always @(posedge clk) begin
  if (reset) en_proc = 1'b0;
  else       en_proc = 1'b1;
end

always begin
  #2.5 clk = ~clk;
end
  

reg[2:0] bx_in_MatchCalculator;
initial bx_in_MatchCalculator = 3'b110;
always begin
  #540 bx_in_MatchCalculator <= bx_in_MatchCalculator + 1'b1;
end
wire[2:0] bx_out_MatchCalculator;

reg MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC17_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC17_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC18_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC18_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC19_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC19_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC20_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC20_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC21_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC21_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC22_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC22_nentries_7_V_dout;
reg MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_wea;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_writeaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_0_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_0_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_1_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_1_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_2_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_2_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_3_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_3_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_4_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_4_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_5_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_5_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_6_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_6_V_din;
reg MCALC_L1L2XXH_L3PHIC23_nentries_7_V_we;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_7_V_din;
wire MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_enb;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_readaddr;
wire[13:0] MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_0_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_1_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_2_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_3_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_4_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_5_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_6_V_dout;
wire[7:0] MCALC_L1L2XXH_L3PHIC23_nentries_7_V_dout;

reg allproj_dataarray_data_V_wea;
wire[7:0] allproj_dataarray_data_V_writeaddr;
wire[59:0] allproj_dataarray_data_V_din;
reg allproj_nentries_0_V_we;
wire[7:0] allproj_nentries_0_V_din;
reg allproj_nentries_1_V_we;
wire[7:0] allproj_nentries_1_V_din;
reg allproj_nentries_2_V_we;
wire[7:0] allproj_nentries_2_V_din;
reg allproj_nentries_3_V_we;
wire[7:0] allproj_nentries_3_V_din;
reg allproj_nentries_4_V_we;
wire[7:0] allproj_nentries_4_V_din;
reg allproj_nentries_5_V_we;
wire[7:0] allproj_nentries_5_V_din;
reg allproj_nentries_6_V_we;
wire[7:0] allproj_nentries_6_V_din;
reg allproj_nentries_7_V_we;
wire[7:0] allproj_nentries_7_V_din;
wire allproj_dataarray_data_V_enb;
wire[9:0] allproj_dataarray_data_V_readaddr;
wire[59:0] allproj_dataarray_data_V_dout;
wire[7:0] allproj_nentries_0_V_dout;
wire[7:0] allproj_nentries_1_V_dout;
wire[7:0] allproj_nentries_2_V_dout;
wire[7:0] allproj_nentries_3_V_dout;
wire[7:0] allproj_nentries_4_V_dout;
wire[7:0] allproj_nentries_5_V_dout;
wire[7:0] allproj_nentries_6_V_dout;
wire[7:0] allproj_nentries_7_V_dout;
reg allstub_dataarray_data_V_wea;
wire[7:0] allstub_dataarray_data_V_writeaddr;
wire[35:0] allstub_dataarray_data_V_din;
reg allstub_nentries_0_V_we;
wire[7:0] allstub_nentries_0_V_din;
reg allstub_nentries_1_V_we;
wire[7:0] allstub_nentries_1_V_din;
reg allstub_nentries_2_V_we;
wire[7:0] allstub_nentries_2_V_din;
reg allstub_nentries_3_V_we;
wire[7:0] allstub_nentries_3_V_din;
reg allstub_nentries_4_V_we;
wire[7:0] allstub_nentries_4_V_din;
reg allstub_nentries_5_V_we;
wire[7:0] allstub_nentries_5_V_din;
reg allstub_nentries_6_V_we;
wire[7:0] allstub_nentries_6_V_din;
reg allstub_nentries_7_V_we;
wire[7:0] allstub_nentries_7_V_din;
wire allstub_dataarray_data_V_enb;
wire[9:0] allstub_dataarray_data_V_readaddr;
wire[35:0] allstub_dataarray_data_V_dout;
wire[7:0] allstub_nentries_0_V_dout;
wire[7:0] allstub_nentries_1_V_dout;
wire[7:0] allstub_nentries_2_V_dout;
wire[7:0] allstub_nentries_3_V_dout;
wire[7:0] allstub_nentries_4_V_dout;
wire[7:0] allstub_nentries_5_V_dout;
wire[7:0] allstub_nentries_6_V_dout;
wire[7:0] allstub_nentries_7_V_dout;

//always @(posedge clk) $display("0x%h\t0x%h\t0x%14h\t0x%8h", bx_out_MatchCalculator, MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_dout, allproj_dataarray_data_V_dout, allstub_dataarray_data_V_dout);

wire FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_0_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_0_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_1_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_1_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_2_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_2_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_3_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_3_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_4_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_4_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_5_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_5_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_6_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_6_V_din;
wire FMCALC_L1L2XXH_L3PHIC_nentries_7_V_we;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_7_V_din;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_readaddr;
wire FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_L1L2XXH_L3PHIC_nentries_7_V_dout;
wire FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_0_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_0_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_1_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_1_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_2_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_2_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_3_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_3_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_4_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_4_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_5_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_5_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_6_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_6_V_din;
wire FMCALC_L3L4XXH_L1PHIC_nentries_7_V_we;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_7_V_din;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_readaddr;
wire FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_L3L4XXH_L1PHIC_nentries_7_V_dout;
wire FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_0_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_0_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_1_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_1_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_2_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_2_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_3_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_3_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_4_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_4_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_5_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_5_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_6_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_6_V_din;
wire FMCALC_L5L6XXH_L3PHIC_nentries_7_V_we;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_7_V_din;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_readaddr;
wire FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_L5L6XXH_L3PHIC_nentries_7_V_dout;
wire FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_0_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_0_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_1_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_1_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_2_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_2_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_3_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_3_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_4_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_4_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_5_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_5_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_6_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_6_V_din;
wire FMCALC_D1D2XXH_L1PHIC_nentries_7_V_we;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_7_V_din;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_readaddr;
wire FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_D1D2XXH_L1PHIC_nentries_7_V_dout;
wire FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_0_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_0_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_1_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_1_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_2_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_2_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_3_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_3_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_4_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_4_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_5_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_5_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_6_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_6_V_din;
wire FMCALC_D3D4XXH_L1PHIC_nentries_7_V_we;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_7_V_din;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_readaddr;
wire FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_D3D4XXH_L1PHIC_nentries_7_V_dout;
wire FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_0_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_0_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_1_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_1_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_2_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_2_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_3_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_3_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_4_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_4_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_5_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_5_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_6_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_6_V_din;
wire FMCALC_D5D6XXH_L1PHIC_nentries_7_V_we;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_7_V_din;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_readaddr;
wire FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_D5D6XXH_L1PHIC_nentries_7_V_dout;
wire FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_wea;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_writeaddr;
wire[44:0] FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_0_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_0_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_1_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_1_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_2_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_2_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_3_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_3_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_4_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_4_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_5_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_5_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_6_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_6_V_din;
wire FMCALC_L2D1XXH_L1PHIC_nentries_7_V_we;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_7_V_din;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_readaddr;
wire FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_enb;
wire[44:0] FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_0_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_1_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_2_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_3_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_4_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_5_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_6_V_dout;
wire[7:0] FMCALC_L2D1XXH_L1PHIC_nentries_7_V_dout;

initial begin
  MCALC_L1L2XXH_L3PHIC17_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC17_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC18_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC19_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC20_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC21_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC22_nentries_7_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_0_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_1_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_2_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_3_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_4_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_5_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_6_V_we = 1'b1;
  MCALC_L1L2XXH_L3PHIC23_nentries_7_V_we = 1'b1;
end

reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_0 = 8'b00000110; // 6
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_1 = 8'b00000100; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC17_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC17_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC17_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC17_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC17_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC17_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC17_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC17_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC17_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC17_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_0 = 8'b00000010; // 2
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC18_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC18_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC18_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC18_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC18_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC18_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC18_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC18_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC18_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC18_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_0 = 8'b00000100; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC19_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC19_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC19_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC19_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC19_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC19_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC19_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC19_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC19_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC19_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_0 = 8'b00000001; // 1
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC20_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC20_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC20_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC20_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC20_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC20_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC20_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC20_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC20_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC20_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_0 = 8'b00000001; // 1
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC21_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC21_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC21_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC21_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC21_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC21_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC21_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC21_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC21_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC21_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_0 = 8'b00001101; // 13
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC22_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC22_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC22_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC22_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC22_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC22_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC22_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC22_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC22_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC22_nentreg_7;
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_0 = 8'b00001101; // 13
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_1 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_2 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_3 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_4 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_5 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_6 = 8'b00000000; // 4
reg[7:0] MCALC_L1L2XXH_L3PHIC23_nentreg_7 = 8'b00000000; // 4
assign MCALC_L1L2XXH_L3PHIC23_nentries_0_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_0;
assign MCALC_L1L2XXH_L3PHIC23_nentries_1_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_1;
assign MCALC_L1L2XXH_L3PHIC23_nentries_2_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_2;
assign MCALC_L1L2XXH_L3PHIC23_nentries_3_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_3;
assign MCALC_L1L2XXH_L3PHIC23_nentries_4_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_4;
assign MCALC_L1L2XXH_L3PHIC23_nentries_5_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_5;
assign MCALC_L1L2XXH_L3PHIC23_nentries_6_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_6;
assign MCALC_L1L2XXH_L3PHIC23_nentries_7_V_din = MCALC_L1L2XXH_L3PHIC23_nentreg_7;

wire[7:0] allproj_nentries_0 = 8'b01101100; // 108;
wire[7:0] allproj_nentries_1 = 8'b01101100; // 108;
assign allproj_nentries_0_V_din = allproj_nentries_0;
assign allproj_nentries_1_V_din = allproj_nentries_1;
wire[7:0] allstub_nentries_0 = 8'b11111111; // 255;
wire[7:0] allstub_nentries_1 = 8'b11111111; // 255;
assign allstub_nentries_0_V_din = allstub_nentries_0;
assign allstub_nentries_1_V_din = allstub_nentries_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC17_04.dat")
) MCALC_L1L2XXH_L3PHIC17 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC17_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC17_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC17_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC17_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC17_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC17_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC17_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC17_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC17_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC17_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC17_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC17_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC17_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC17_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC17_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC17_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC17_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC17_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC17_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC17_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC17_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC17_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC17_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC17_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC18_04.dat")
) MCALC_L1L2XXH_L3PHIC18 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC18_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC18_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC18_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC18_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC18_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC18_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC18_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC18_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC18_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC18_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC18_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC18_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC18_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC18_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC18_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC18_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC18_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC18_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC18_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC18_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC18_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC18_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC18_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC18_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC19_04.dat")
) MCALC_L1L2XXH_L3PHIC19 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_dout),
  .nent_we0(MCALC_L1L2XXH_L3PHIC19_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC19_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC19_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC19_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC19_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC19_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC19_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC19_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC19_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC19_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC19_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC19_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC19_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC19_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC19_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC19_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC19_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC19_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC19_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC19_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC19_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC19_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC19_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC19_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC20_04.dat")
) MCALC_L1L2XXH_L3PHIC20 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC20_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC20_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC20_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC20_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC20_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC20_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC20_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC20_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC20_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC20_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC20_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC20_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC20_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC20_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC20_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC20_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC20_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC20_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC20_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC20_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC20_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC20_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC20_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC20_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC21_04.dat")
) MCALC_L1L2XXH_L3PHIC21 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC21_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC21_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC21_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC21_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC21_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC21_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC21_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC21_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC21_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC21_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC21_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC21_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC21_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC21_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC21_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC21_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC21_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC21_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC21_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC21_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC21_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC21_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC21_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC21_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC22_04.dat")
) MCALC_L1L2XXH_L3PHIC22 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC22_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC22_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC22_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC22_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC22_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC22_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC22_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC22_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC22_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC22_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC22_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC22_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC22_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC22_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC22_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC22_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC22_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC22_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC22_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC22_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC22_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC22_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC22_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC22_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CandidateMatches_CM_L3PHIC23_04.dat")
) MCALC_L1L2XXH_L3PHIC23 (
  .clka(clk),
  .clkb(clk),
  .wea(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_wea),
  .addra(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_writeaddr),
  .dina(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_din),
  .nent_we0(MCALC_L1L2XXH_L3PHIC23_nentries_0_V_we),
  .nent_i0(MCALC_L1L2XXH_L3PHIC23_nentries_0_V_din),
  .nent_we1(MCALC_L1L2XXH_L3PHIC23_nentries_1_V_we),
  .nent_i1(MCALC_L1L2XXH_L3PHIC23_nentries_1_V_din),
  /*
  .nent_we2(MCALC_L1L2XXH_L3PHIC23_nentries_2_V_we),
  .nent_i2(MCALC_L1L2XXH_L3PHIC23_nentries_2_V_din),
  .nent_we3(MCALC_L1L2XXH_L3PHIC23_nentries_3_V_we),
  .nent_i3(MCALC_L1L2XXH_L3PHIC23_nentries_3_V_din),
  .nent_we4(MCALC_L1L2XXH_L3PHIC23_nentries_4_V_we),
  .nent_i4(MCALC_L1L2XXH_L3PHIC23_nentries_4_V_din),
  .nent_we5(MCALC_L1L2XXH_L3PHIC23_nentries_5_V_we),
  .nent_i5(MCALC_L1L2XXH_L3PHIC23_nentries_5_V_din),
  .nent_we6(MCALC_L1L2XXH_L3PHIC23_nentries_6_V_we),
  .nent_i6(MCALC_L1L2XXH_L3PHIC23_nentries_6_V_din),
  .nent_we7(MCALC_L1L2XXH_L3PHIC23_nentries_7_V_we),
  .nent_i7(MCALC_L1L2XXH_L3PHIC23_nentries_7_V_din),
  */
  .enb(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_enb),
  .addrb(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_readaddr),
  .doutb(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_dout),
  .nent_o0(MCALC_L1L2XXH_L3PHIC23_nentries_0_V_dout),
  .nent_o1(MCALC_L1L2XXH_L3PHIC23_nentries_1_V_dout),
  /*
  .nent_o2(MCALC_L1L2XXH_L3PHIC23_nentries_2_V_dout),
  .nent_o3(MCALC_L1L2XXH_L3PHIC23_nentries_3_V_dout),
  .nent_o4(MCALC_L1L2XXH_L3PHIC23_nentries_4_V_dout),
  .nent_o5(MCALC_L1L2XXH_L3PHIC23_nentries_5_V_dout),
  .nent_o6(MCALC_L1L2XXH_L3PHIC23_nentries_6_V_dout),
  .nent_o7(MCALC_L1L2XXH_L3PHIC23_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("AllProj_AP_L3PHIC_04.dat")
) allproj_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(allproj_dataarray_data_V_wea),
  .addra(allproj_dataarray_data_V_writeaddr),
  .dina(allproj_dataarray_data_V_din),
  .nent_we0(allproj_nentries_0_V_we),
  .nent_i0(allproj_nentries_0_V_din),
  .nent_we1(allproj_nentries_1_V_we),
  .nent_i1(allproj_nentries_1_V_din),
  .nent_we2(allproj_nentries_2_V_we),
  .nent_i2(allproj_nentries_2_V_din),
  .nent_we3(allproj_nentries_3_V_we),
  .nent_i3(allproj_nentries_3_V_din),
  .nent_we4(allproj_nentries_4_V_we),
  .nent_i4(allproj_nentries_4_V_din),
  .nent_we5(allproj_nentries_5_V_we),
  .nent_i5(allproj_nentries_5_V_din),
  .nent_we6(allproj_nentries_6_V_we),
  .nent_i6(allproj_nentries_6_V_din),
  .nent_we7(allproj_nentries_7_V_we),
  .nent_i7(allproj_nentries_7_V_din),
  .enb(allproj_dataarray_data_V_enb),
  .addrb(allproj_dataarray_data_V_readaddr),
  .doutb(allproj_dataarray_data_V_dout),
  .nent_o0(allproj_nentries_0_V_dout),
  .nent_o1(allproj_nentries_1_V_dout),
  .nent_o2(allproj_nentries_2_V_dout),
  .nent_o3(allproj_nentries_3_V_dout),
  .nent_o4(allproj_nentries_4_V_dout),
  .nent_o5(allproj_nentries_5_V_dout),
  .nent_o6(allproj_nentries_6_V_dout),
  .nent_o7(allproj_nentries_7_V_dout),
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(36),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("AllStubs_AS_L3PHICn4_04.dat")
) allstub_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(allstub_dataarray_data_V_wea),
  .addra(allstub_dataarray_data_V_writeaddr),
  .dina(allstub_dataarray_data_V_din),
  .nent_we0(allstub_nentries_0_V_we),
  .nent_i0(allstub_nentries_0_V_din),
  .nent_we1(allstub_nentries_1_V_we),
  .nent_i1(allstub_nentries_1_V_din),
  .nent_we2(allstub_nentries_2_V_we),
  .nent_i2(allstub_nentries_2_V_din),
  .nent_we3(allstub_nentries_3_V_we),
  .nent_i3(allstub_nentries_3_V_din),
  .nent_we4(allstub_nentries_4_V_we),
  .nent_i4(allstub_nentries_4_V_din),
  .nent_we5(allstub_nentries_5_V_we),
  .nent_i5(allstub_nentries_5_V_din),
  .nent_we6(allstub_nentries_6_V_we),
  .nent_i6(allstub_nentries_6_V_din),
  .nent_we7(allstub_nentries_7_V_we),
  .nent_i7(allstub_nentries_7_V_din),
  .enb(allstub_dataarray_data_V_enb),
  .addrb(allstub_dataarray_data_V_readaddr),
  .doutb(allstub_dataarray_data_V_dout),
  .nent_o0(allstub_nentries_0_V_dout),
  .nent_o1(allstub_nentries_1_V_dout),
  .nent_o2(allstub_nentries_2_V_dout),
  .nent_o3(allstub_nentries_3_V_dout),
  .nent_o4(allstub_nentries_4_V_dout),
  .nent_o5(allstub_nentries_5_V_dout),
  .nent_o6(allstub_nentries_6_V_dout),
  .nent_o7(allstub_nentries_7_V_dout),
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_L1L2XXH_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_wea),
  .addra(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_L1L2XXH_L3PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_L1L2XXH_L3PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_L1L2XXH_L3PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_L1L2XXH_L3PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_L1L2XXH_L3PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_L1L2XXH_L3PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_L1L2XXH_L3PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_L1L2XXH_L3PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_L1L2XXH_L3PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_L1L2XXH_L3PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_L1L2XXH_L3PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_L1L2XXH_L3PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_L1L2XXH_L3PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_L1L2XXH_L3PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_L1L2XXH_L3PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_L1L2XXH_L3PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_L1L2XXH_L3PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_L1L2XXH_L3PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_L1L2XXH_L3PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_L1L2XXH_L3PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_L1L2XXH_L3PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_L1L2XXH_L3PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_L1L2XXH_L3PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_L1L2XXH_L3PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_L3L4XXH_L1PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_wea),
  .addra(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_L3L4XXH_L1PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_L3L4XXH_L1PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_L3L4XXH_L1PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_L3L4XXH_L1PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_L3L4XXH_L1PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_L3L4XXH_L1PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_L3L4XXH_L1PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_L3L4XXH_L1PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_L3L4XXH_L1PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_L3L4XXH_L1PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_L3L4XXH_L1PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_L3L4XXH_L1PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_L3L4XXH_L1PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_L3L4XXH_L1PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_L3L4XXH_L1PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_L3L4XXH_L1PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_L3L4XXH_L1PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_L3L4XXH_L1PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_L3L4XXH_L1PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_L3L4XXH_L1PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_L3L4XXH_L1PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_L3L4XXH_L1PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_L3L4XXH_L1PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_L3L4XXH_L1PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_L5L6XXH_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_wea),
  .addra(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_L5L6XXH_L3PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_L5L6XXH_L3PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_L5L6XXH_L3PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_L5L6XXH_L3PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_L5L6XXH_L3PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_L5L6XXH_L3PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_L5L6XXH_L3PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_L5L6XXH_L3PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_L5L6XXH_L3PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_L5L6XXH_L3PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_L5L6XXH_L3PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_L5L6XXH_L3PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_L5L6XXH_L3PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_L5L6XXH_L3PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_L5L6XXH_L3PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_L5L6XXH_L3PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_L5L6XXH_L3PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_L5L6XXH_L3PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_L5L6XXH_L3PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_L5L6XXH_L3PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_L5L6XXH_L3PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_L5L6XXH_L3PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_L5L6XXH_L3PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_L5L6XXH_L3PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_D1D2XXH_L1PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_wea),
  .addra(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_D1D2XXH_L1PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_D1D2XXH_L1PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_D1D2XXH_L1PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_D1D2XXH_L1PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_D1D2XXH_L1PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_D1D2XXH_L1PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_D1D2XXH_L1PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_D1D2XXH_L1PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_D1D2XXH_L1PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_D1D2XXH_L1PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_D1D2XXH_L1PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_D1D2XXH_L1PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_D1D2XXH_L1PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_D1D2XXH_L1PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_D1D2XXH_L1PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_D1D2XXH_L1PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_D1D2XXH_L1PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_D1D2XXH_L1PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_D1D2XXH_L1PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_D1D2XXH_L1PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_D1D2XXH_L1PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_D1D2XXH_L1PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_D1D2XXH_L1PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_D1D2XXH_L1PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_D3D4XXH_L1PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_wea),
  .addra(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_D3D4XXH_L1PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_D3D4XXH_L1PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_D3D4XXH_L1PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_D3D4XXH_L1PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_D3D4XXH_L1PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_D3D4XXH_L1PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_D3D4XXH_L1PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_D3D4XXH_L1PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_D3D4XXH_L1PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_D3D4XXH_L1PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_D3D4XXH_L1PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_D3D4XXH_L1PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_D3D4XXH_L1PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_D3D4XXH_L1PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_D3D4XXH_L1PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_D3D4XXH_L1PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_dout),
  /*
  .nent_o0(FMCALC_D3D4XXH_L1PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_D3D4XXH_L1PHIC_nentries_1_V_dout),
  .nent_o2(FMCALC_D3D4XXH_L1PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_D3D4XXH_L1PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_D3D4XXH_L1PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_D3D4XXH_L1PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_D3D4XXH_L1PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_D3D4XXH_L1PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_D5D6XXH_L1PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_wea),
  .addra(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_D5D6XXH_L1PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_D5D6XXH_L1PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_D5D6XXH_L1PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_D5D6XXH_L1PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_D5D6XXH_L1PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_D5D6XXH_L1PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_D5D6XXH_L1PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_D5D6XXH_L1PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_D5D6XXH_L1PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_D5D6XXH_L1PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_D5D6XXH_L1PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_D5D6XXH_L1PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_D5D6XXH_L1PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_D5D6XXH_L1PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_D5D6XXH_L1PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_D5D6XXH_L1PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_D5D6XXH_L1PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_D5D6XXH_L1PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_D5D6XXH_L1PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_D5D6XXH_L1PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_D5D6XXH_L1PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_D5D6XXH_L1PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_D5D6XXH_L1PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_D5D6XXH_L1PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FMCALC_L2D1XXH_L1PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_wea),
  .addra(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_writeaddr),
  .dina(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_din),
  .nent_we0(FMCALC_L2D1XXH_L1PHIC_nentries_0_V_we),
  .nent_i0(FMCALC_L2D1XXH_L1PHIC_nentries_0_V_din),
  .nent_we1(FMCALC_L2D1XXH_L1PHIC_nentries_1_V_we),
  .nent_i1(FMCALC_L2D1XXH_L1PHIC_nentries_1_V_din),
  /*
  .nent_we2(FMCALC_L2D1XXH_L1PHIC_nentries_2_V_we),
  .nent_i2(FMCALC_L2D1XXH_L1PHIC_nentries_2_V_din),
  .nent_we3(FMCALC_L2D1XXH_L1PHIC_nentries_3_V_we),
  .nent_i3(FMCALC_L2D1XXH_L1PHIC_nentries_3_V_din),
  .nent_we4(FMCALC_L2D1XXH_L1PHIC_nentries_4_V_we),
  .nent_i4(FMCALC_L2D1XXH_L1PHIC_nentries_4_V_din),
  .nent_we5(FMCALC_L2D1XXH_L1PHIC_nentries_5_V_we),
  .nent_i5(FMCALC_L2D1XXH_L1PHIC_nentries_5_V_din),
  .nent_we6(FMCALC_L2D1XXH_L1PHIC_nentries_6_V_we),
  .nent_i6(FMCALC_L2D1XXH_L1PHIC_nentries_6_V_din),
  .nent_we7(FMCALC_L2D1XXH_L1PHIC_nentries_7_V_we),
  .nent_i7(FMCALC_L2D1XXH_L1PHIC_nentries_7_V_din),
  */
  .enb(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_enb),
  .addrb(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_readaddr),
  .doutb(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_dout),
  .nent_o0(FMCALC_L2D1XXH_L1PHIC_nentries_0_V_dout),
  .nent_o1(FMCALC_L2D1XXH_L1PHIC_nentries_1_V_dout),
  /*
  .nent_o2(FMCALC_L2D1XXH_L1PHIC_nentries_2_V_dout),
  .nent_o3(FMCALC_L2D1XXH_L1PHIC_nentries_3_V_dout),
  .nent_o4(FMCALC_L2D1XXH_L1PHIC_nentries_4_V_dout),
  .nent_o5(FMCALC_L2D1XXH_L1PHIC_nentries_5_V_dout),
  .nent_o6(FMCALC_L2D1XXH_L1PHIC_nentries_6_V_dout),
  .nent_o7(FMCALC_L2D1XXH_L1PHIC_nentries_7_V_dout),
  */
  .regceb(1'b1)
);


SectorProcessor SectorProcessor_inst (
    .ap_clk(clk),
    .ap_rst(reset),
    .ap_start(en_proc),
    .bx_V(bx_in_MatchCalculator),
    .match1_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_readaddr),
    .match1_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_enb),
    .match1_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC17_dataarray_data_V_dout),
    .match1_nentries_0_V(MCALC_L1L2XXH_L3PHIC17_nentries_0_V_dout),
    .match1_nentries_1_V(MCALC_L1L2XXH_L3PHIC17_nentries_1_V_dout),
    /*
    .match1_nentries_2_V(MCALC_L1L2XXH_L3PHIC17_nentries_2_V_dout),
    .match1_nentries_3_V(MCALC_L1L2XXH_L3PHIC17_nentries_3_V_dout),
    .match1_nentries_4_V(MCALC_L1L2XXH_L3PHIC17_nentries_4_V_dout),
    .match1_nentries_5_V(MCALC_L1L2XXH_L3PHIC17_nentries_5_V_dout),
    .match1_nentries_6_V(MCALC_L1L2XXH_L3PHIC17_nentries_6_V_dout),
    .match1_nentries_7_V(MCALC_L1L2XXH_L3PHIC17_nentries_7_V_dout),
    */
    .match2_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_readaddr),
    .match2_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_enb),
    .match2_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC18_dataarray_data_V_dout),
    .match2_nentries_0_V(MCALC_L1L2XXH_L3PHIC18_nentries_0_V_dout),
    .match2_nentries_1_V(MCALC_L1L2XXH_L3PHIC18_nentries_1_V_dout),
    /*
    .match2_nentries_2_V(MCALC_L1L2XXH_L3PHIC18_nentries_2_V_dout),
    .match2_nentries_3_V(MCALC_L1L2XXH_L3PHIC18_nentries_3_V_dout),
    .match2_nentries_4_V(MCALC_L1L2XXH_L3PHIC18_nentries_4_V_dout),
    .match2_nentries_5_V(MCALC_L1L2XXH_L3PHIC18_nentries_5_V_dout),
    .match2_nentries_6_V(MCALC_L1L2XXH_L3PHIC18_nentries_6_V_dout),
    .match2_nentries_7_V(MCALC_L1L2XXH_L3PHIC18_nentries_7_V_dout),
    */
    .match3_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_readaddr),
    .match3_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_enb),
    .match3_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC19_dataarray_data_V_dout),
    .match3_nentries_0_V(MCALC_L1L2XXH_L3PHIC19_nentries_0_V_dout),
    .match3_nentries_1_V(MCALC_L1L2XXH_L3PHIC19_nentries_1_V_dout),
    /*
    .match3_nentries_2_V(MCALC_L1L2XXH_L3PHIC19_nentries_2_V_dout),
    .match3_nentries_3_V(MCALC_L1L2XXH_L3PHIC19_nentries_3_V_dout),
    .match3_nentries_4_V(MCALC_L1L2XXH_L3PHIC19_nentries_4_V_dout),
    .match3_nentries_5_V(MCALC_L1L2XXH_L3PHIC19_nentries_5_V_dout),
    .match3_nentries_6_V(MCALC_L1L2XXH_L3PHIC19_nentries_6_V_dout),
    .match3_nentries_7_V(MCALC_L1L2XXH_L3PHIC19_nentries_7_V_dout),
    */
    .match4_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_readaddr),
    .match4_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_enb),
    .match4_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC20_dataarray_data_V_dout),
    .match4_nentries_0_V(MCALC_L1L2XXH_L3PHIC20_nentries_0_V_dout),
    .match4_nentries_1_V(MCALC_L1L2XXH_L3PHIC20_nentries_1_V_dout),
    /*
    .match4_nentries_2_V(MCALC_L1L2XXH_L3PHIC20_nentries_2_V_dout),
    .match4_nentries_3_V(MCALC_L1L2XXH_L3PHIC20_nentries_3_V_dout),
    .match4_nentries_4_V(MCALC_L1L2XXH_L3PHIC20_nentries_4_V_dout),
    .match4_nentries_5_V(MCALC_L1L2XXH_L3PHIC20_nentries_5_V_dout),
    .match4_nentries_6_V(MCALC_L1L2XXH_L3PHIC20_nentries_6_V_dout),
    .match4_nentries_7_V(MCALC_L1L2XXH_L3PHIC20_nentries_7_V_dout),
    */
    .match5_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_readaddr),
    .match5_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_enb),
    .match5_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC21_dataarray_data_V_dout),
    .match5_nentries_0_V(MCALC_L1L2XXH_L3PHIC21_nentries_0_V_dout),
    .match5_nentries_1_V(MCALC_L1L2XXH_L3PHIC21_nentries_1_V_dout),
    /*
    .match5_nentries_2_V(MCALC_L1L2XXH_L3PHIC21_nentries_2_V_dout),
    .match5_nentries_3_V(MCALC_L1L2XXH_L3PHIC21_nentries_3_V_dout),
    .match5_nentries_4_V(MCALC_L1L2XXH_L3PHIC21_nentries_4_V_dout),
    .match5_nentries_5_V(MCALC_L1L2XXH_L3PHIC21_nentries_5_V_dout),
    .match5_nentries_6_V(MCALC_L1L2XXH_L3PHIC21_nentries_6_V_dout),
    .match5_nentries_7_V(MCALC_L1L2XXH_L3PHIC21_nentries_7_V_dout),
    */
    .match6_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_readaddr),
    .match6_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_enb),
    .match6_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC22_dataarray_data_V_dout),
    .match6_nentries_0_V(MCALC_L1L2XXH_L3PHIC22_nentries_0_V_dout),
    .match6_nentries_1_V(MCALC_L1L2XXH_L3PHIC22_nentries_1_V_dout),
    /*
    .match6_nentries_2_V(MCALC_L1L2XXH_L3PHIC22_nentries_2_V_dout),
    .match6_nentries_3_V(MCALC_L1L2XXH_L3PHIC22_nentries_3_V_dout),
    .match6_nentries_4_V(MCALC_L1L2XXH_L3PHIC22_nentries_4_V_dout),
    .match6_nentries_5_V(MCALC_L1L2XXH_L3PHIC22_nentries_5_V_dout),
    .match6_nentries_6_V(MCALC_L1L2XXH_L3PHIC22_nentries_6_V_dout),
    .match6_nentries_7_V(MCALC_L1L2XXH_L3PHIC22_nentries_7_V_dout),
    */
    .match7_dataarray_data_V_readaddr(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_readaddr),
    .match7_dataarray_data_V_enb(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_enb),
    .match7_dataarray_data_V_dout(MCALC_L1L2XXH_L3PHIC23_dataarray_data_V_dout),
    .match7_nentries_0_V(MCALC_L1L2XXH_L3PHIC23_nentries_0_V_dout),
    .match7_nentries_1_V(MCALC_L1L2XXH_L3PHIC23_nentries_1_V_dout),
    /*
    .match7_nentries_2_V(MCALC_L1L2XXH_L3PHIC23_nentries_2_V_dout),
    .match7_nentries_3_V(MCALC_L1L2XXH_L3PHIC23_nentries_3_V_dout),
    .match7_nentries_4_V(MCALC_L1L2XXH_L3PHIC23_nentries_4_V_dout),
    .match7_nentries_5_V(MCALC_L1L2XXH_L3PHIC23_nentries_5_V_dout),
    .match7_nentries_6_V(MCALC_L1L2XXH_L3PHIC23_nentries_6_V_dout),
    .match7_nentries_7_V(MCALC_L1L2XXH_L3PHIC23_nentries_7_V_dout),
    */
    .allstub_dataarray_data_V_readaddr(allstub_dataarray_data_V_readaddr),
    .allstub_dataarray_data_V_enb(allstub_dataarray_data_V_enb),
    .allstub_dataarray_data_V_dout(allstub_dataarray_data_V_dout),
    .allstub_nentries_0_V(allstub_nentries_0_V_dout),
    .allstub_nentries_1_V(allstub_nentries_1_V_dout),
    /*
    .allstub_nentries_2_V(allstub_nentries_2_V_dout),
    .allstub_nentries_3_V(allstub_nentries_3_V_dout),
    .allstub_nentries_4_V(allstub_nentries_4_V_dout),
    .allstub_nentries_5_V(allstub_nentries_5_V_dout),
    .allstub_nentries_6_V(allstub_nentries_6_V_dout),
    .allstub_nentries_7_V(allstub_nentries_7_V_dout),
    */
    .allproj_dataarray_data_V_readaddr(allproj_dataarray_data_V_readaddr),
    .allproj_dataarray_data_V_enb(allproj_dataarray_data_V_enb),
    .allproj_dataarray_data_V_dout(allproj_dataarray_data_V_dout),
    .allproj_nentries_0_V(allproj_nentries_0_V_dout),
    .allproj_nentries_1_V(allproj_nentries_1_V_dout),
    /*
    .allproj_nentries_2_V(allproj_nentries_2_V_dout),
    .allproj_nentries_3_V(allproj_nentries_3_V_dout),
    .allproj_nentries_4_V(allproj_nentries_4_V_dout),
    .allproj_nentries_5_V(allproj_nentries_5_V_dout),
    .allproj_nentries_6_V(allproj_nentries_6_V_dout),
    .allproj_nentries_7_V(allproj_nentries_7_V_dout),
    */
    .bx_o_V(bx_out_MatchCalculator),
    .fullmatch1_dataarray_data_V_writeaddr(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr),
    .fullmatch1_dataarray_data_V_we0(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_wea),
    .fullmatch1_dataarray_data_V_din(FMCALC_L1L2XXH_L3PHIC_dataarray_data_V_din),
    .fullmatch1_nentries_0_V(FMCALC_L1L2XXH_L3PHIC_nentries_0_V_din),
    .fullmatch1_nentries_1_V(FMCALC_L1L2XXH_L3PHIC_nentries_1_V_din),
    /*
    .fullmatch1_nentries_2_V(FMCALC_L1L2XXH_L3PHIC_nentries_2_V_din),
    .fullmatch1_nentries_3_V(FMCALC_L1L2XXH_L3PHIC_nentries_3_V_din),
    .fullmatch1_nentries_4_V(FMCALC_L1L2XXH_L3PHIC_nentries_4_V_din),
    .fullmatch1_nentries_5_V(FMCALC_L1L2XXH_L3PHIC_nentries_5_V_din),
    .fullmatch1_nentries_6_V(FMCALC_L1L2XXH_L3PHIC_nentries_6_V_din),
    .fullmatch1_nentries_7_V(FMCALC_L1L2XXH_L3PHIC_nentries_7_V_din),
    */
    .fullmatch1_nentries_0_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_0_V_we),
    .fullmatch1_nentries_1_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_1_V_we),
    /*
    .fullmatch1_nentries_2_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_2_V_we),
    .fullmatch1_nentries_3_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_3_V_we),
    .fullmatch1_nentries_4_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_4_V_we),
    .fullmatch1_nentries_5_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_5_V_we),
    .fullmatch1_nentries_6_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_6_V_we),
    .fullmatch1_nentries_7_V_ap_vld(FMCALC_L1L2XXH_L3PHIC_nentries_7_V_we),
    */
    .fullmatch2_dataarray_data_V_writeaddr(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_writeaddr),
    .fullmatch2_dataarray_data_V_we0(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_wea),
    .fullmatch2_dataarray_data_V_din(FMCALC_L3L4XXH_L1PHIC_dataarray_data_V_din),
    .fullmatch2_nentries_0_V(FMCALC_L3L4XXH_L1PHIC_nentries_0_V_din),
    .fullmatch2_nentries_1_V(FMCALC_L3L4XXH_L1PHIC_nentries_1_V_din),
    /*
    .fullmatch2_nentries_2_V(FMCALC_L3L4XXH_L1PHIC_nentries_2_V_din),
    .fullmatch2_nentries_3_V(FMCALC_L3L4XXH_L1PHIC_nentries_3_V_din),
    .fullmatch2_nentries_4_V(FMCALC_L3L4XXH_L1PHIC_nentries_4_V_din),
    .fullmatch2_nentries_5_V(FMCALC_L3L4XXH_L1PHIC_nentries_5_V_din),
    .fullmatch2_nentries_6_V(FMCALC_L3L4XXH_L1PHIC_nentries_6_V_din),
    .fullmatch2_nentries_7_V(FMCALC_L3L4XXH_L1PHIC_nentries_7_V_din),
    */
    .fullmatch2_nentries_0_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_0_V_we),
    .fullmatch2_nentries_1_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_1_V_we),
    /*
    .fullmatch2_nentries_2_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_2_V_we),
    .fullmatch2_nentries_3_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_3_V_we),
    .fullmatch2_nentries_4_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_4_V_we),
    .fullmatch2_nentries_5_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_5_V_we),
    .fullmatch2_nentries_6_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_6_V_we),
    .fullmatch2_nentries_7_V_ap_vld(FMCALC_L3L4XXH_L1PHIC_nentries_7_V_we),
    */
    .fullmatch3_dataarray_data_V_writeaddr(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_writeaddr),
    .fullmatch3_dataarray_data_V_we0(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_wea),
    .fullmatch3_dataarray_data_V_din(FMCALC_L5L6XXH_L3PHIC_dataarray_data_V_din),
    .fullmatch3_nentries_0_V(FMCALC_L5L6XXH_L3PHIC_nentries_0_V_din),
    .fullmatch3_nentries_1_V(FMCALC_L5L6XXH_L3PHIC_nentries_1_V_din),
    /*
    .fullmatch3_nentries_2_V(FMCALC_L5L6XXH_L3PHIC_nentries_2_V_din),
    .fullmatch3_nentries_3_V(FMCALC_L5L6XXH_L3PHIC_nentries_3_V_din),
    .fullmatch3_nentries_4_V(FMCALC_L5L6XXH_L3PHIC_nentries_4_V_din),
    .fullmatch3_nentries_5_V(FMCALC_L5L6XXH_L3PHIC_nentries_5_V_din),
    .fullmatch3_nentries_6_V(FMCALC_L5L6XXH_L3PHIC_nentries_6_V_din),
    .fullmatch3_nentries_7_V(FMCALC_L5L6XXH_L3PHIC_nentries_7_V_din),
    */
    .fullmatch3_nentries_0_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_0_V_we),
    .fullmatch3_nentries_1_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_1_V_we),
    /*
    .fullmatch3_nentries_2_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_2_V_we),
    .fullmatch3_nentries_3_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_3_V_we),
    .fullmatch3_nentries_4_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_4_V_we),
    .fullmatch3_nentries_5_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_5_V_we),
    .fullmatch3_nentries_6_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_6_V_we),
    .fullmatch3_nentries_7_V_ap_vld(FMCALC_L5L6XXH_L3PHIC_nentries_7_V_we),
    */
    .fullmatch4_dataarray_data_V_writeaddr(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_writeaddr),
    .fullmatch4_dataarray_data_V_we0(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_wea),
    .fullmatch4_dataarray_data_V_din(FMCALC_D1D2XXH_L1PHIC_dataarray_data_V_din),
    .fullmatch4_nentries_0_V(FMCALC_D1D2XXH_L1PHIC_nentries_0_V_din),
    .fullmatch4_nentries_1_V(FMCALC_D1D2XXH_L1PHIC_nentries_1_V_din),
    /*
    .fullmatch4_nentries_2_V(FMCALC_D1D2XXH_L1PHIC_nentries_2_V_din),
    .fullmatch4_nentries_3_V(FMCALC_D1D2XXH_L1PHIC_nentries_3_V_din),
    .fullmatch4_nentries_4_V(FMCALC_D1D2XXH_L1PHIC_nentries_4_V_din),
    .fullmatch4_nentries_5_V(FMCALC_D1D2XXH_L1PHIC_nentries_5_V_din),
    .fullmatch4_nentries_6_V(FMCALC_D1D2XXH_L1PHIC_nentries_6_V_din),
    .fullmatch4_nentries_7_V(FMCALC_D1D2XXH_L1PHIC_nentries_7_V_din),
    */
    .fullmatch4_nentries_0_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_0_V_we),
    .fullmatch4_nentries_1_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_1_V_we),
    /*
    .fullmatch4_nentries_2_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_2_V_we),
    .fullmatch4_nentries_3_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_3_V_we),
    .fullmatch4_nentries_4_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_4_V_we),
    .fullmatch4_nentries_5_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_5_V_we),
    .fullmatch4_nentries_6_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_6_V_we),
    .fullmatch4_nentries_7_V_ap_vld(FMCALC_D1D2XXH_L1PHIC_nentries_7_V_we),
    */
    .fullmatch5_dataarray_data_V_writeaddr(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_writeaddr),
    .fullmatch5_dataarray_data_V_we0(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_wea),
    .fullmatch5_dataarray_data_V_din(FMCALC_D3D4XXH_L1PHIC_dataarray_data_V_din),
    .fullmatch5_nentries_0_V(FMCALC_D3D4XXH_L1PHIC_nentries_0_V_din),
    .fullmatch5_nentries_1_V(FMCALC_D3D4XXH_L1PHIC_nentries_1_V_din),
    /*
    .fullmatch5_nentries_2_V(FMCALC_D3D4XXH_L1PHIC_nentries_2_V_din),
    .fullmatch5_nentries_3_V(FMCALC_D3D4XXH_L1PHIC_nentries_3_V_din),
    .fullmatch5_nentries_4_V(FMCALC_D3D4XXH_L1PHIC_nentries_4_V_din),
    .fullmatch5_nentries_5_V(FMCALC_D3D4XXH_L1PHIC_nentries_5_V_din),
    .fullmatch5_nentries_6_V(FMCALC_D3D4XXH_L1PHIC_nentries_6_V_din),
    .fullmatch5_nentries_7_V(FMCALC_D3D4XXH_L1PHIC_nentries_7_V_din),
    */
    .fullmatch5_nentries_0_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_0_V_we),
    .fullmatch5_nentries_1_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_1_V_we),
    /*
    .fullmatch5_nentries_2_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_2_V_we),
    .fullmatch5_nentries_3_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_3_V_we),
    .fullmatch5_nentries_4_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_4_V_we),
    .fullmatch5_nentries_5_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_5_V_we),
    .fullmatch5_nentries_6_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_6_V_we),
    .fullmatch5_nentries_7_V_ap_vld(FMCALC_D3D4XXH_L1PHIC_nentries_7_V_we),
    */
    .fullmatch6_dataarray_data_V_writeaddr(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_writeaddr),
    .fullmatch6_dataarray_data_V_we0(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_wea),
    .fullmatch6_dataarray_data_V_din(FMCALC_D5D6XXH_L1PHIC_dataarray_data_V_din),
    .fullmatch6_nentries_0_V(FMCALC_D5D6XXH_L1PHIC_nentries_0_V_din),
    .fullmatch6_nentries_1_V(FMCALC_D5D6XXH_L1PHIC_nentries_1_V_din),
    /*
    .fullmatch6_nentries_2_V(FMCALC_D5D6XXH_L1PHIC_nentries_2_V_din),
    .fullmatch6_nentries_3_V(FMCALC_D5D6XXH_L1PHIC_nentries_3_V_din),
    .fullmatch6_nentries_4_V(FMCALC_D5D6XXH_L1PHIC_nentries_4_V_din),
    .fullmatch6_nentries_5_V(FMCALC_D5D6XXH_L1PHIC_nentries_5_V_din),
    .fullmatch6_nentries_6_V(FMCALC_D5D6XXH_L1PHIC_nentries_6_V_din),
    .fullmatch6_nentries_7_V(FMCALC_D5D6XXH_L1PHIC_nentries_7_V_din),
    */
    .fullmatch6_nentries_0_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_0_V_we),
    .fullmatch6_nentries_1_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_1_V_we),
    /*
    .fullmatch6_nentries_2_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_2_V_we),
    .fullmatch6_nentries_3_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_3_V_we),
    .fullmatch6_nentries_4_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_4_V_we),
    .fullmatch6_nentries_5_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_5_V_we),
    .fullmatch6_nentries_6_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_6_V_we),
    .fullmatch6_nentries_7_V_ap_vld(FMCALC_D5D6XXH_L1PHIC_nentries_7_V_we),
    */
    .fullmatch7_dataarray_data_V_writeaddr(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_writeaddr),
    .fullmatch7_dataarray_data_V_we0(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_wea),
    .fullmatch7_dataarray_data_V_din(FMCALC_L2D1XXH_L1PHIC_dataarray_data_V_din),
    .fullmatch7_nentries_0_V(FMCALC_L2D1XXH_L1PHIC_nentries_0_V_din),
    .fullmatch7_nentries_1_V(FMCALC_L2D1XXH_L1PHIC_nentries_1_V_din),
    /*
    .fullmatch7_nentries_2_V(FMCALC_L2D1XXH_L1PHIC_nentries_2_V_din),
    .fullmatch7_nentries_3_V(FMCALC_L2D1XXH_L1PHIC_nentries_3_V_din),
    .fullmatch7_nentries_4_V(FMCALC_L2D1XXH_L1PHIC_nentries_4_V_din),
    .fullmatch7_nentries_5_V(FMCALC_L2D1XXH_L1PHIC_nentries_5_V_din),
    .fullmatch7_nentries_6_V(FMCALC_L2D1XXH_L1PHIC_nentries_6_V_din),
    .fullmatch7_nentries_7_V(FMCALC_L2D1XXH_L1PHIC_nentries_7_V_din),
    */
    .fullmatch7_nentries_0_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_0_V_we),
    .fullmatch7_nentries_1_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_1_V_we)
    /*
    .fullmatch7_nentries_2_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_2_V_we),
    .fullmatch7_nentries_3_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_3_V_we),
    .fullmatch7_nentries_4_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_4_V_we),
    .fullmatch7_nentries_5_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_5_V_we),
    .fullmatch7_nentries_6_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_6_V_we),
    .fullmatch7_nentries_7_V_ap_vld(FMCALC_L2D1XXH_L1PHIC_nentries_7_V_we)
    */
);

endmodule
