// Test bench generated by generator_verilog.py

`timescale 1ns / 1ps

module SectorProcessor_test();

reg clk;
reg reset;

initial begin
  reset = 1'b1;
  clk   = 1'b1;
end

initial begin
  #1080
  reset = 1'b0;
end

reg en_proc = 1'b0;
always @(posedge clk) begin
  if (reset) en_proc = 1'b0;
  else       en_proc = 1'b1;
end

always begin
  #2.5 clk = ~clk;
end

reg[2:0] bx_in_MatchCalculator;
initial bx_in_MatchCalculator = 3'b110;
always begin
  #540 bx_in_MatchCalculator <= bx_in_MatchCalculator + 1'b1;
end
wire[2:0] bx_out_MatchCalculator;

reg CM_L3PHIC20_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC20_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC20_dataarray_data_V_din;
reg CM_L3PHIC20_nentries_0_V_we;
wire[7:0] CM_L3PHIC20_nentries_0_V_din;
reg CM_L3PHIC20_nentries_1_V_we;
wire[7:0] CM_L3PHIC20_nentries_1_V_din;
wire CM_L3PHIC20_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC20_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC20_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC20_nentries_0_V_dout;
wire[7:0] CM_L3PHIC20_nentries_1_V_dout;

initial begin
  CM_L3PHIC20_nentries_0_V_we = 1'b1;
  CM_L3PHIC20_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC20_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC20_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC20_nentries_0_V_din = CM_L3PHIC20_nentreg_0;
assign CM_L3PHIC20_nentries_1_V_din = CM_L3PHIC20_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC20.dat")
) CM_L3PHIC20 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC20_dataarray_data_V_wea),
  .addra(CM_L3PHIC20_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC20_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC20_nentries_0_V_we),
  .nent_i0(CM_L3PHIC20_nentries_0_V_din),
  .nent_we1(CM_L3PHIC20_nentries_1_V_we),
  .nent_i1(CM_L3PHIC20_nentries_1_V_din),
  .enb(CM_L3PHIC20_dataarray_data_V_enb),
  .addrb(CM_L3PHIC20_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC20_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC20_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC20_nentries_1_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC21_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC21_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC21_dataarray_data_V_din;
reg CM_L3PHIC21_nentries_0_V_we;
wire[7:0] CM_L3PHIC21_nentries_0_V_din;
reg CM_L3PHIC21_nentries_1_V_we;
wire[7:0] CM_L3PHIC21_nentries_1_V_din;
wire CM_L3PHIC21_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC21_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC21_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC21_nentries_0_V_dout;
wire[7:0] CM_L3PHIC21_nentries_1_V_dout;

initial begin
  CM_L3PHIC21_nentries_0_V_we = 1'b1;
  CM_L3PHIC21_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC21_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC21_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC21_nentries_0_V_din = CM_L3PHIC21_nentreg_0;
assign CM_L3PHIC21_nentries_1_V_din = CM_L3PHIC21_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC21.dat")
) CM_L3PHIC21 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC21_dataarray_data_V_wea),
  .addra(CM_L3PHIC21_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC21_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC21_nentries_0_V_we),
  .nent_i0(CM_L3PHIC21_nentries_0_V_din),
  .nent_we1(CM_L3PHIC21_nentries_1_V_we),
  .nent_i1(CM_L3PHIC21_nentries_1_V_din),
  .enb(CM_L3PHIC21_dataarray_data_V_enb),
  .addrb(CM_L3PHIC21_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC21_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC21_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC21_nentries_1_V_dout),
  .regceb(1'b1)
);

reg AS_L3PHICn4_dataarray_data_V_wea;
wire[9:0] AS_L3PHICn4_dataarray_data_V_writeaddr;
wire[35:0] AS_L3PHICn4_dataarray_data_V_din;
reg AS_L3PHICn4_nentries_0_V_we;
wire[7:0] AS_L3PHICn4_nentries_0_V_din;
reg AS_L3PHICn4_nentries_1_V_we;
wire[7:0] AS_L3PHICn4_nentries_1_V_din;
reg AS_L3PHICn4_nentries_2_V_we;
wire[7:0] AS_L3PHICn4_nentries_2_V_din;
reg AS_L3PHICn4_nentries_3_V_we;
wire[7:0] AS_L3PHICn4_nentries_3_V_din;
reg AS_L3PHICn4_nentries_4_V_we;
wire[7:0] AS_L3PHICn4_nentries_4_V_din;
reg AS_L3PHICn4_nentries_5_V_we;
wire[7:0] AS_L3PHICn4_nentries_5_V_din;
reg AS_L3PHICn4_nentries_6_V_we;
wire[7:0] AS_L3PHICn4_nentries_6_V_din;
reg AS_L3PHICn4_nentries_7_V_we;
wire[7:0] AS_L3PHICn4_nentries_7_V_din;
wire AS_L3PHICn4_dataarray_data_V_enb;
wire[9:0] AS_L3PHICn4_dataarray_data_V_readaddr;
wire[35:0] AS_L3PHICn4_dataarray_data_V_dout;
wire[7:0] AS_L3PHICn4_nentries_0_V_dout;
wire[7:0] AS_L3PHICn4_nentries_1_V_dout;
wire[7:0] AS_L3PHICn4_nentries_2_V_dout;
wire[7:0] AS_L3PHICn4_nentries_3_V_dout;
wire[7:0] AS_L3PHICn4_nentries_4_V_dout;
wire[7:0] AS_L3PHICn4_nentries_5_V_dout;
wire[7:0] AS_L3PHICn4_nentries_6_V_dout;
wire[7:0] AS_L3PHICn4_nentries_7_V_dout;

initial begin
  AS_L3PHICn4_nentries_0_V_we = 1'b1;
  AS_L3PHICn4_nentries_1_V_we = 1'b1;
  AS_L3PHICn4_nentries_2_V_we = 1'b1;
  AS_L3PHICn4_nentries_3_V_we = 1'b1;
  AS_L3PHICn4_nentries_4_V_we = 1'b1;
  AS_L3PHICn4_nentries_5_V_we = 1'b1;
  AS_L3PHICn4_nentries_6_V_we = 1'b1;
  AS_L3PHICn4_nentries_7_V_we = 1'b1;
end

reg[7:0] AS_L3PHICn4_nentreg_0 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_1 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_2 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_3 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_4 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_5 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_6 = 8'b00001001; // FIX
reg[7:0] AS_L3PHICn4_nentreg_7 = 8'b00001001; // FIX
assign AS_L3PHICn4_nentries_0_V_din = AS_L3PHICn4_nentreg_0;
assign AS_L3PHICn4_nentries_1_V_din = AS_L3PHICn4_nentreg_1;
assign AS_L3PHICn4_nentries_2_V_din = AS_L3PHICn4_nentreg_2;
assign AS_L3PHICn4_nentries_3_V_din = AS_L3PHICn4_nentreg_3;
assign AS_L3PHICn4_nentries_4_V_din = AS_L3PHICn4_nentreg_4;
assign AS_L3PHICn4_nentries_5_V_din = AS_L3PHICn4_nentreg_5;
assign AS_L3PHICn4_nentries_6_V_din = AS_L3PHICn4_nentreg_6;
assign AS_L3PHICn4_nentries_7_V_din = AS_L3PHICn4_nentreg_7;

Memory #(
  .RAM_WIDTH(36),
  .RAM_DEPTH(1024),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("AS_L3PHICn4.dat")
) AS_L3PHICn4 (
  .clka(clk),
  .clkb(clk),
  .wea(AS_L3PHICn4_dataarray_data_V_wea),
  .addra(AS_L3PHICn4_dataarray_data_V_writeaddr),
  .dina(AS_L3PHICn4_dataarray_data_V_din),
  .nent_we0(AS_L3PHICn4_nentries_0_V_we),
  .nent_i0(AS_L3PHICn4_nentries_0_V_din),
  .nent_we1(AS_L3PHICn4_nentries_1_V_we),
  .nent_i1(AS_L3PHICn4_nentries_1_V_din),
  .nent_we2(AS_L3PHICn4_nentries_2_V_we),
  .nent_i2(AS_L3PHICn4_nentries_2_V_din),
  .nent_we3(AS_L3PHICn4_nentries_3_V_we),
  .nent_i3(AS_L3PHICn4_nentries_3_V_din),
  .nent_we4(AS_L3PHICn4_nentries_4_V_we),
  .nent_i4(AS_L3PHICn4_nentries_4_V_din),
  .nent_we5(AS_L3PHICn4_nentries_5_V_we),
  .nent_i5(AS_L3PHICn4_nentries_5_V_din),
  .nent_we6(AS_L3PHICn4_nentries_6_V_we),
  .nent_i6(AS_L3PHICn4_nentries_6_V_din),
  .nent_we7(AS_L3PHICn4_nentries_7_V_we),
  .nent_i7(AS_L3PHICn4_nentries_7_V_din),
  .enb(AS_L3PHICn4_dataarray_data_V_enb),
  .addrb(AS_L3PHICn4_dataarray_data_V_readaddr),
  .doutb(AS_L3PHICn4_dataarray_data_V_dout),
  .nent_o0(AS_L3PHICn4_nentries_0_V_dout),
  .nent_o1(AS_L3PHICn4_nentries_1_V_dout),
  .nent_o2(AS_L3PHICn4_nentries_2_V_dout),
  .nent_o3(AS_L3PHICn4_nentries_3_V_dout),
  .nent_o4(AS_L3PHICn4_nentries_4_V_dout),
  .nent_o5(AS_L3PHICn4_nentries_5_V_dout),
  .nent_o6(AS_L3PHICn4_nentries_6_V_dout),
  .nent_o7(AS_L3PHICn4_nentries_7_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC22_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC22_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC22_dataarray_data_V_din;
reg CM_L3PHIC22_nentries_0_V_we;
wire[7:0] CM_L3PHIC22_nentries_0_V_din;
reg CM_L3PHIC22_nentries_1_V_we;
wire[7:0] CM_L3PHIC22_nentries_1_V_din;
wire CM_L3PHIC22_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC22_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC22_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC22_nentries_0_V_dout;
wire[7:0] CM_L3PHIC22_nentries_1_V_dout;

initial begin
  CM_L3PHIC22_nentries_0_V_we = 1'b1;
  CM_L3PHIC22_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC22_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC22_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC22_nentries_0_V_din = CM_L3PHIC22_nentreg_0;
assign CM_L3PHIC22_nentries_1_V_din = CM_L3PHIC22_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC22.dat")
) CM_L3PHIC22 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC22_dataarray_data_V_wea),
  .addra(CM_L3PHIC22_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC22_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC22_nentries_0_V_we),
  .nent_i0(CM_L3PHIC22_nentries_0_V_din),
  .nent_we1(CM_L3PHIC22_nentries_1_V_we),
  .nent_i1(CM_L3PHIC22_nentries_1_V_din),
  .enb(CM_L3PHIC22_dataarray_data_V_enb),
  .addrb(CM_L3PHIC22_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC22_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC22_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC22_nentries_1_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC23_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC23_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC23_dataarray_data_V_din;
reg CM_L3PHIC23_nentries_0_V_we;
wire[7:0] CM_L3PHIC23_nentries_0_V_din;
reg CM_L3PHIC23_nentries_1_V_we;
wire[7:0] CM_L3PHIC23_nentries_1_V_din;
wire CM_L3PHIC23_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC23_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC23_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC23_nentries_0_V_dout;
wire[7:0] CM_L3PHIC23_nentries_1_V_dout;

initial begin
  CM_L3PHIC23_nentries_0_V_we = 1'b1;
  CM_L3PHIC23_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC23_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC23_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC23_nentries_0_V_din = CM_L3PHIC23_nentreg_0;
assign CM_L3PHIC23_nentries_1_V_din = CM_L3PHIC23_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC23.dat")
) CM_L3PHIC23 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC23_dataarray_data_V_wea),
  .addra(CM_L3PHIC23_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC23_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC23_nentries_0_V_we),
  .nent_i0(CM_L3PHIC23_nentries_0_V_din),
  .nent_we1(CM_L3PHIC23_nentries_1_V_we),
  .nent_i1(CM_L3PHIC23_nentries_1_V_din),
  .enb(CM_L3PHIC23_dataarray_data_V_enb),
  .addrb(CM_L3PHIC23_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC23_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC23_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC23_nentries_1_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC24_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC24_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC24_dataarray_data_V_din;
reg CM_L3PHIC24_nentries_0_V_we;
wire[7:0] CM_L3PHIC24_nentries_0_V_din;
reg CM_L3PHIC24_nentries_1_V_we;
wire[7:0] CM_L3PHIC24_nentries_1_V_din;
wire CM_L3PHIC24_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC24_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC24_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC24_nentries_0_V_dout;
wire[7:0] CM_L3PHIC24_nentries_1_V_dout;

initial begin
  CM_L3PHIC24_nentries_0_V_we = 1'b1;
  CM_L3PHIC24_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC24_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC24_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC24_nentries_0_V_din = CM_L3PHIC24_nentreg_0;
assign CM_L3PHIC24_nentries_1_V_din = CM_L3PHIC24_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC24.dat")
) CM_L3PHIC24 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC24_dataarray_data_V_wea),
  .addra(CM_L3PHIC24_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC24_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC24_nentries_0_V_we),
  .nent_i0(CM_L3PHIC24_nentries_0_V_din),
  .nent_we1(CM_L3PHIC24_nentries_1_V_we),
  .nent_i1(CM_L3PHIC24_nentries_1_V_din),
  .enb(CM_L3PHIC24_dataarray_data_V_enb),
  .addrb(CM_L3PHIC24_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC24_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC24_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC24_nentries_1_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC17_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC17_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC17_dataarray_data_V_din;
reg CM_L3PHIC17_nentries_0_V_we;
wire[7:0] CM_L3PHIC17_nentries_0_V_din;
reg CM_L3PHIC17_nentries_1_V_we;
wire[7:0] CM_L3PHIC17_nentries_1_V_din;
wire CM_L3PHIC17_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC17_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC17_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC17_nentries_0_V_dout;
wire[7:0] CM_L3PHIC17_nentries_1_V_dout;

initial begin
  CM_L3PHIC17_nentries_0_V_we = 1'b1;
  CM_L3PHIC17_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC17_nentreg_0 = 8'b00000110; // FIX
reg[7:0] CM_L3PHIC17_nentreg_1 = 8'b00000100; // FIX
assign CM_L3PHIC17_nentries_0_V_din = CM_L3PHIC17_nentreg_0;
assign CM_L3PHIC17_nentries_1_V_din = CM_L3PHIC17_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC17.dat")
) CM_L3PHIC17 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC17_dataarray_data_V_wea),
  .addra(CM_L3PHIC17_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC17_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC17_nentries_0_V_we),
  .nent_i0(CM_L3PHIC17_nentries_0_V_din),
  .nent_we1(CM_L3PHIC17_nentries_1_V_we),
  .nent_i1(CM_L3PHIC17_nentries_1_V_din),
  .enb(CM_L3PHIC17_dataarray_data_V_enb),
  .addrb(CM_L3PHIC17_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC17_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC17_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC17_nentries_1_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC18_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC18_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC18_dataarray_data_V_din;
reg CM_L3PHIC18_nentries_0_V_we;
wire[7:0] CM_L3PHIC18_nentries_0_V_din;
reg CM_L3PHIC18_nentries_1_V_we;
wire[7:0] CM_L3PHIC18_nentries_1_V_din;
wire CM_L3PHIC18_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC18_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC18_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC18_nentries_0_V_dout;
wire[7:0] CM_L3PHIC18_nentries_1_V_dout;

initial begin
  CM_L3PHIC18_nentries_0_V_we = 1'b1;
  CM_L3PHIC18_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC18_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC18_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC18_nentries_0_V_din = CM_L3PHIC18_nentreg_0;
assign CM_L3PHIC18_nentries_1_V_din = CM_L3PHIC18_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC18.dat")
) CM_L3PHIC18 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC18_dataarray_data_V_wea),
  .addra(CM_L3PHIC18_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC18_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC18_nentries_0_V_we),
  .nent_i0(CM_L3PHIC18_nentries_0_V_din),
  .nent_we1(CM_L3PHIC18_nentries_1_V_we),
  .nent_i1(CM_L3PHIC18_nentries_1_V_din),
  .enb(CM_L3PHIC18_dataarray_data_V_enb),
  .addrb(CM_L3PHIC18_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC18_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC18_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC18_nentries_1_V_dout),
  .regceb(1'b1)
);

reg AP_L3PHIC_dataarray_data_V_wea;
wire[9:0] AP_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] AP_L3PHIC_dataarray_data_V_din;
reg AP_L3PHIC_nentries_0_V_we;
wire[7:0] AP_L3PHIC_nentries_0_V_din;
reg AP_L3PHIC_nentries_1_V_we;
wire[7:0] AP_L3PHIC_nentries_1_V_din;
reg AP_L3PHIC_nentries_2_V_we;
wire[7:0] AP_L3PHIC_nentries_2_V_din;
reg AP_L3PHIC_nentries_3_V_we;
wire[7:0] AP_L3PHIC_nentries_3_V_din;
reg AP_L3PHIC_nentries_4_V_we;
wire[7:0] AP_L3PHIC_nentries_4_V_din;
reg AP_L3PHIC_nentries_5_V_we;
wire[7:0] AP_L3PHIC_nentries_5_V_din;
reg AP_L3PHIC_nentries_6_V_we;
wire[7:0] AP_L3PHIC_nentries_6_V_din;
reg AP_L3PHIC_nentries_7_V_we;
wire[7:0] AP_L3PHIC_nentries_7_V_din;
wire AP_L3PHIC_dataarray_data_V_enb;
wire[9:0] AP_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] AP_L3PHIC_dataarray_data_V_dout;
wire[7:0] AP_L3PHIC_nentries_0_V_dout;
wire[7:0] AP_L3PHIC_nentries_1_V_dout;
wire[7:0] AP_L3PHIC_nentries_2_V_dout;
wire[7:0] AP_L3PHIC_nentries_3_V_dout;
wire[7:0] AP_L3PHIC_nentries_4_V_dout;
wire[7:0] AP_L3PHIC_nentries_5_V_dout;
wire[7:0] AP_L3PHIC_nentries_6_V_dout;
wire[7:0] AP_L3PHIC_nentries_7_V_dout;

initial begin
  AP_L3PHIC_nentries_0_V_we = 1'b1;
  AP_L3PHIC_nentries_1_V_we = 1'b1;
  AP_L3PHIC_nentries_2_V_we = 1'b1;
  AP_L3PHIC_nentries_3_V_we = 1'b1;
  AP_L3PHIC_nentries_4_V_we = 1'b1;
  AP_L3PHIC_nentries_5_V_we = 1'b1;
  AP_L3PHIC_nentries_6_V_we = 1'b1;
  AP_L3PHIC_nentries_7_V_we = 1'b1;
end

reg[7:0] AP_L3PHIC_nentreg_0 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_1 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_2 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_3 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_4 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_5 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_6 = 8'b00001001; // FIX
reg[7:0] AP_L3PHIC_nentreg_7 = 8'b00001001; // FIX
assign AP_L3PHIC_nentries_0_V_din = AP_L3PHIC_nentreg_0;
assign AP_L3PHIC_nentries_1_V_din = AP_L3PHIC_nentreg_1;
assign AP_L3PHIC_nentries_2_V_din = AP_L3PHIC_nentreg_2;
assign AP_L3PHIC_nentries_3_V_din = AP_L3PHIC_nentreg_3;
assign AP_L3PHIC_nentries_4_V_din = AP_L3PHIC_nentreg_4;
assign AP_L3PHIC_nentries_5_V_din = AP_L3PHIC_nentreg_5;
assign AP_L3PHIC_nentries_6_V_din = AP_L3PHIC_nentreg_6;
assign AP_L3PHIC_nentries_7_V_din = AP_L3PHIC_nentreg_7;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(1024),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("AP_L3PHIC.dat")
) AP_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(AP_L3PHIC_dataarray_data_V_wea),
  .addra(AP_L3PHIC_dataarray_data_V_writeaddr),
  .dina(AP_L3PHIC_dataarray_data_V_din),
  .nent_we0(AP_L3PHIC_nentries_0_V_we),
  .nent_i0(AP_L3PHIC_nentries_0_V_din),
  .nent_we1(AP_L3PHIC_nentries_1_V_we),
  .nent_i1(AP_L3PHIC_nentries_1_V_din),
  .nent_we2(AP_L3PHIC_nentries_2_V_we),
  .nent_i2(AP_L3PHIC_nentries_2_V_din),
  .nent_we3(AP_L3PHIC_nentries_3_V_we),
  .nent_i3(AP_L3PHIC_nentries_3_V_din),
  .nent_we4(AP_L3PHIC_nentries_4_V_we),
  .nent_i4(AP_L3PHIC_nentries_4_V_din),
  .nent_we5(AP_L3PHIC_nentries_5_V_we),
  .nent_i5(AP_L3PHIC_nentries_5_V_din),
  .nent_we6(AP_L3PHIC_nentries_6_V_we),
  .nent_i6(AP_L3PHIC_nentries_6_V_din),
  .nent_we7(AP_L3PHIC_nentries_7_V_we),
  .nent_i7(AP_L3PHIC_nentries_7_V_din),
  .enb(AP_L3PHIC_dataarray_data_V_enb),
  .addrb(AP_L3PHIC_dataarray_data_V_readaddr),
  .doutb(AP_L3PHIC_dataarray_data_V_dout),
  .nent_o0(AP_L3PHIC_nentries_0_V_dout),
  .nent_o1(AP_L3PHIC_nentries_1_V_dout),
  .nent_o2(AP_L3PHIC_nentries_2_V_dout),
  .nent_o3(AP_L3PHIC_nentries_3_V_dout),
  .nent_o4(AP_L3PHIC_nentries_4_V_dout),
  .nent_o5(AP_L3PHIC_nentries_5_V_dout),
  .nent_o6(AP_L3PHIC_nentries_6_V_dout),
  .nent_o7(AP_L3PHIC_nentries_7_V_dout),
  .regceb(1'b1)
);

reg CM_L3PHIC19_dataarray_data_V_wea;
wire[7:0] CM_L3PHIC19_dataarray_data_V_writeaddr;
wire[13:0] CM_L3PHIC19_dataarray_data_V_din;
reg CM_L3PHIC19_nentries_0_V_we;
wire[7:0] CM_L3PHIC19_nentries_0_V_din;
reg CM_L3PHIC19_nentries_1_V_we;
wire[7:0] CM_L3PHIC19_nentries_1_V_din;
wire CM_L3PHIC19_dataarray_data_V_enb;
wire[7:0] CM_L3PHIC19_dataarray_data_V_readaddr;
wire[13:0] CM_L3PHIC19_dataarray_data_V_dout;
wire[7:0] CM_L3PHIC19_nentries_0_V_dout;
wire[7:0] CM_L3PHIC19_nentries_1_V_dout;

initial begin
  CM_L3PHIC19_nentries_0_V_we = 1'b1;
  CM_L3PHIC19_nentries_1_V_we = 1'b1;
end

reg[7:0] CM_L3PHIC19_nentreg_0 = 8'b00001001; // FIX
reg[7:0] CM_L3PHIC19_nentreg_1 = 8'b00001001; // FIX
assign CM_L3PHIC19_nentries_0_V_din = CM_L3PHIC19_nentreg_0;
assign CM_L3PHIC19_nentries_1_V_din = CM_L3PHIC19_nentreg_1;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("CM_L3PHIC19.dat")
) CM_L3PHIC19 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L3PHIC19_dataarray_data_V_wea),
  .addra(CM_L3PHIC19_dataarray_data_V_writeaddr),
  .dina(CM_L3PHIC19_dataarray_data_V_din),
  .nent_we0(CM_L3PHIC19_nentries_0_V_we),
  .nent_i0(CM_L3PHIC19_nentries_0_V_din),
  .nent_we1(CM_L3PHIC19_nentries_1_V_we),
  .nent_i1(CM_L3PHIC19_nentries_1_V_din),
  .enb(CM_L3PHIC19_dataarray_data_V_enb),
  .addrb(CM_L3PHIC19_dataarray_data_V_readaddr),
  .doutb(CM_L3PHIC19_dataarray_data_V_dout),
  .nent_o0(CM_L3PHIC19_nentries_0_V_dout),
  .nent_o1(CM_L3PHIC19_nentries_1_V_dout),
  .regceb(1'b1)
);


wire FM_L1L2XX_L3PHIC_dataarray_data_V_wea;
wire[7:0] FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FM_L1L2XX_L3PHIC_dataarray_data_V_din;
wire FM_L1L2XX_L3PHIC_nentries_0_V_we;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_0_V_din;
wire FM_L1L2XX_L3PHIC_nentries_1_V_we;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_1_V_din;
wire FM_L1L2XX_L3PHIC_dataarray_data_V_enb;
wire[7:0] FM_L1L2XX_L3PHIC_dataarray_data_V_readaddr;
wire[44:0] FM_L1L2XX_L3PHIC_dataarray_data_V_dout;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_0_V_dout;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_1_V_dout;

reg[13:0] CM_L3PHIC17_dataarray_data_V_doutMSB;
reg[6:0] CM_L3PHIC17_dataarray_data_V_doutLSB; 
always @(posedge clk) begin
    CM_L3PHIC17_dataarray_data_V_doutMSB = CM_L3PHIC17_dataarray_data_V_dout;
    CM_L3PHIC17_dataarray_data_V_doutMSB = (CM_L3PHIC17_dataarray_data_V_doutMSB>>7);
    CM_L3PHIC17_dataarray_data_V_doutLSB = CM_L3PHIC17_dataarray_data_V_dout;
    $display("0x%\h\t0x%\h\t0x%h\t0x%h\t0x%h\t0x%h\t%b\t0x%h", bx_out_MatchCalculator, CM_L3PHIC17_dataarray_data_V_dout, CM_L3PHIC17_dataarray_data_V_doutMSB, CM_L3PHIC17_dataarray_data_V_doutLSB, AP_L3PHIC_dataarray_data_V_dout, AS_L3PHICn4_dataarray_data_V_dout, FM_L1L2XX_L3PHIC_dataarray_data_V_din, FM_L1L2XX_L3PHIC_dataarray_data_V_din);
end

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FM_L1L2XX_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FM_L1L2XX_L3PHIC_dataarray_data_V_wea),
  .addra(FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FM_L1L2XX_L3PHIC_dataarray_data_V_din),
  .nent_we0(FM_L1L2XX_L3PHIC_nentries_0_V_we),
  .nent_i0(FM_L1L2XX_L3PHIC_nentries_0_V_din),
  .nent_we1(FM_L1L2XX_L3PHIC_nentries_1_V_we),
  .nent_i1(FM_L1L2XX_L3PHIC_nentries_1_V_din),
  .enb(FM_L1L2XX_L3PHIC_dataarray_data_V_enb),
  .addrb(FM_L1L2XX_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FM_L1L2XX_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FM_L1L2XX_L3PHIC_nentries_0_V_dout),
  .nent_o1(FM_L1L2XX_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire FM_L5L6XX_L3PHIC_dataarray_data_V_wea;
wire[7:0] FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FM_L5L6XX_L3PHIC_dataarray_data_V_din;
wire FM_L5L6XX_L3PHIC_nentries_0_V_we;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_0_V_din;
wire FM_L5L6XX_L3PHIC_nentries_1_V_we;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_1_V_din;
wire FM_L5L6XX_L3PHIC_dataarray_data_V_enb;
wire[7:0] FM_L5L6XX_L3PHIC_dataarray_data_V_readaddr;
wire[44:0] FM_L5L6XX_L3PHIC_dataarray_data_V_dout;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_0_V_dout;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FM_L5L6XX_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FM_L5L6XX_L3PHIC_dataarray_data_V_wea),
  .addra(FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FM_L5L6XX_L3PHIC_dataarray_data_V_din),
  .nent_we0(FM_L5L6XX_L3PHIC_nentries_0_V_we),
  .nent_i0(FM_L5L6XX_L3PHIC_nentries_0_V_din),
  .nent_we1(FM_L5L6XX_L3PHIC_nentries_1_V_we),
  .nent_i1(FM_L5L6XX_L3PHIC_nentries_1_V_din),
  .enb(FM_L5L6XX_L3PHIC_dataarray_data_V_enb),
  .addrb(FM_L5L6XX_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FM_L5L6XX_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FM_L5L6XX_L3PHIC_nentries_0_V_dout),
  .nent_o1(FM_L5L6XX_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);



SectorProcessor SectorProcessor_inst (
  .clk(clk),
  .reset(reset),
  .en_proc(en_proc),
  .bx_in_MatchCalculator(bx_in_MatchCalculator),
  .CM_L3PHIC17_dataarray_data_V_enb(CM_L3PHIC17_dataarray_data_V_enb),
  .CM_L3PHIC17_dataarray_data_V_readaddr(CM_L3PHIC17_dataarray_data_V_readaddr),
  .CM_L3PHIC17_dataarray_data_V_dout(CM_L3PHIC17_dataarray_data_V_dout),
  .CM_L3PHIC17_nentries_0_V_dout(CM_L3PHIC17_nentries_0_V_dout),
  .CM_L3PHIC17_nentries_1_V_dout(CM_L3PHIC17_nentries_1_V_dout),
  .CM_L3PHIC18_dataarray_data_V_enb(CM_L3PHIC18_dataarray_data_V_enb),
  .CM_L3PHIC18_dataarray_data_V_readaddr(CM_L3PHIC18_dataarray_data_V_readaddr),
  .CM_L3PHIC18_dataarray_data_V_dout(CM_L3PHIC18_dataarray_data_V_dout),
  .CM_L3PHIC18_nentries_0_V_dout(CM_L3PHIC18_nentries_0_V_dout),
  .CM_L3PHIC18_nentries_1_V_dout(CM_L3PHIC18_nentries_1_V_dout),
  .CM_L3PHIC19_dataarray_data_V_enb(CM_L3PHIC19_dataarray_data_V_enb),
  .CM_L3PHIC19_dataarray_data_V_readaddr(CM_L3PHIC19_dataarray_data_V_readaddr),
  .CM_L3PHIC19_dataarray_data_V_dout(CM_L3PHIC19_dataarray_data_V_dout),
  .CM_L3PHIC19_nentries_0_V_dout(CM_L3PHIC19_nentries_0_V_dout),
  .CM_L3PHIC19_nentries_1_V_dout(CM_L3PHIC19_nentries_1_V_dout),
  .CM_L3PHIC20_dataarray_data_V_enb(CM_L3PHIC20_dataarray_data_V_enb),
  .CM_L3PHIC20_dataarray_data_V_readaddr(CM_L3PHIC20_dataarray_data_V_readaddr),
  .CM_L3PHIC20_dataarray_data_V_dout(CM_L3PHIC20_dataarray_data_V_dout),
  .CM_L3PHIC20_nentries_0_V_dout(CM_L3PHIC20_nentries_0_V_dout),
  .CM_L3PHIC20_nentries_1_V_dout(CM_L3PHIC20_nentries_1_V_dout),
  .CM_L3PHIC21_dataarray_data_V_enb(CM_L3PHIC21_dataarray_data_V_enb),
  .CM_L3PHIC21_dataarray_data_V_readaddr(CM_L3PHIC21_dataarray_data_V_readaddr),
  .CM_L3PHIC21_dataarray_data_V_dout(CM_L3PHIC21_dataarray_data_V_dout),
  .CM_L3PHIC21_nentries_0_V_dout(CM_L3PHIC21_nentries_0_V_dout),
  .CM_L3PHIC21_nentries_1_V_dout(CM_L3PHIC21_nentries_1_V_dout),
  .CM_L3PHIC22_dataarray_data_V_enb(CM_L3PHIC22_dataarray_data_V_enb),
  .CM_L3PHIC22_dataarray_data_V_readaddr(CM_L3PHIC22_dataarray_data_V_readaddr),
  .CM_L3PHIC22_dataarray_data_V_dout(CM_L3PHIC22_dataarray_data_V_dout),
  .CM_L3PHIC22_nentries_0_V_dout(CM_L3PHIC22_nentries_0_V_dout),
  .CM_L3PHIC22_nentries_1_V_dout(CM_L3PHIC22_nentries_1_V_dout),
  .CM_L3PHIC23_dataarray_data_V_enb(CM_L3PHIC23_dataarray_data_V_enb),
  .CM_L3PHIC23_dataarray_data_V_readaddr(CM_L3PHIC23_dataarray_data_V_readaddr),
  .CM_L3PHIC23_dataarray_data_V_dout(CM_L3PHIC23_dataarray_data_V_dout),
  .CM_L3PHIC23_nentries_0_V_dout(CM_L3PHIC23_nentries_0_V_dout),
  .CM_L3PHIC23_nentries_1_V_dout(CM_L3PHIC23_nentries_1_V_dout),
  .CM_L3PHIC24_dataarray_data_V_enb(CM_L3PHIC24_dataarray_data_V_enb),
  .CM_L3PHIC24_dataarray_data_V_readaddr(CM_L3PHIC24_dataarray_data_V_readaddr),
  .CM_L3PHIC24_dataarray_data_V_dout(CM_L3PHIC24_dataarray_data_V_dout),
  .CM_L3PHIC24_nentries_0_V_dout(CM_L3PHIC24_nentries_0_V_dout),
  .CM_L3PHIC24_nentries_1_V_dout(CM_L3PHIC24_nentries_1_V_dout),
  .AS_L3PHICn4_dataarray_data_V_enb(AS_L3PHICn4_dataarray_data_V_enb),
  .AS_L3PHICn4_dataarray_data_V_readaddr(AS_L3PHICn4_dataarray_data_V_readaddr),
  .AS_L3PHICn4_dataarray_data_V_dout(AS_L3PHICn4_dataarray_data_V_dout),
  .AS_L3PHICn4_nentries_0_V_dout(AS_L3PHICn4_nentries_0_V_dout),
  .AS_L3PHICn4_nentries_1_V_dout(AS_L3PHICn4_nentries_1_V_dout),
  .AS_L3PHICn4_nentries_2_V_dout(AS_L3PHICn4_nentries_2_V_dout),
  .AS_L3PHICn4_nentries_3_V_dout(AS_L3PHICn4_nentries_3_V_dout),
  .AS_L3PHICn4_nentries_4_V_dout(AS_L3PHICn4_nentries_4_V_dout),
  .AS_L3PHICn4_nentries_5_V_dout(AS_L3PHICn4_nentries_5_V_dout),
  .AS_L3PHICn4_nentries_6_V_dout(AS_L3PHICn4_nentries_6_V_dout),
  .AS_L3PHICn4_nentries_7_V_dout(AS_L3PHICn4_nentries_7_V_dout),
  .AP_L3PHIC_dataarray_data_V_enb(AP_L3PHIC_dataarray_data_V_enb),
  .AP_L3PHIC_dataarray_data_V_readaddr(AP_L3PHIC_dataarray_data_V_readaddr),
  .AP_L3PHIC_dataarray_data_V_dout(AP_L3PHIC_dataarray_data_V_dout),
  .AP_L3PHIC_nentries_0_V_dout(AP_L3PHIC_nentries_0_V_dout),
  .AP_L3PHIC_nentries_1_V_dout(AP_L3PHIC_nentries_1_V_dout),
  .AP_L3PHIC_nentries_2_V_dout(AP_L3PHIC_nentries_2_V_dout),
  .AP_L3PHIC_nentries_3_V_dout(AP_L3PHIC_nentries_3_V_dout),
  .AP_L3PHIC_nentries_4_V_dout(AP_L3PHIC_nentries_4_V_dout),
  .AP_L3PHIC_nentries_5_V_dout(AP_L3PHIC_nentries_5_V_dout),
  .AP_L3PHIC_nentries_6_V_dout(AP_L3PHIC_nentries_6_V_dout),
  .AP_L3PHIC_nentries_7_V_dout(AP_L3PHIC_nentries_7_V_dout),
  .bx_out_MatchCalculator(bx_out_MatchCalculator),
  .FM_L1L2XX_L3PHIC_dataarray_data_V_wea(FM_L1L2XX_L3PHIC_dataarray_data_V_wea),
  .FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr(FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr),
  .FM_L1L2XX_L3PHIC_dataarray_data_V_din(FM_L1L2XX_L3PHIC_dataarray_data_V_din),
  .FM_L1L2XX_L3PHIC_nentries_0_V_we(FM_L1L2XX_L3PHIC_nentries_0_V_we),
  .FM_L1L2XX_L3PHIC_nentries_0_V_din(FM_L1L2XX_L3PHIC_nentries_0_V_din),
  .FM_L1L2XX_L3PHIC_nentries_1_V_we(FM_L1L2XX_L3PHIC_nentries_1_V_we),
  .FM_L1L2XX_L3PHIC_nentries_1_V_din(FM_L1L2XX_L3PHIC_nentries_1_V_din),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_wea(FM_L5L6XX_L3PHIC_dataarray_data_V_wea),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr(FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_din(FM_L5L6XX_L3PHIC_dataarray_data_V_din),
  .FM_L5L6XX_L3PHIC_nentries_0_V_we(FM_L5L6XX_L3PHIC_nentries_0_V_we),
  .FM_L5L6XX_L3PHIC_nentries_0_V_din(FM_L5L6XX_L3PHIC_nentries_0_V_din),
  .FM_L5L6XX_L3PHIC_nentries_1_V_we(FM_L5L6XX_L3PHIC_nentries_1_V_we),
  .FM_L5L6XX_L3PHIC_nentries_1_V_din(FM_L5L6XX_L3PHIC_nentries_1_V_din)
);

endmodule
